import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import StyledComponentsRegistry from '../../styles/styled-component/registry'
import { ThemeProvider } from 'styled-components'
import Theme from '../../styles/styled-component/theme'
import GlobalStyles from '../../styles/styled-component/globar_styles'

const poppins = Poppins({ weight:['300', '400', '500', '600', '700', '800'], subsets:['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <StyledComponentsRegistry>
          <GlobalStyles/>
          <Theme>
            {children}
          </Theme>
        </StyledComponentsRegistry>
        </body>
    </html>
  )
}
