
import { Metadata } from "next/types";
import styles from "./admin.module.css";
import React, { useState } from "react";
import CustomSideBar from "@/components/ui/CustomSideBar";
import { SideNavBar } from "@/components/ui";

export const metadata: Metadata = {
  title: "Cedar Hills | Admin",
  description: "Generated by create next app",
};

const AdminRootLayout = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  
  return (
    <>
      <div className={styles["admin-app"]}>
        <div className={styles["nav-bar-container"]}></div>
        <div className={styles["container"]}>
          <div className={styles["side-navbar"]}>
            <SideNavBar/>
          </div>
          <div>{children}</div>
        </div>
      </div>
    </>
  );
};

export default AdminRootLayout;
